// Code generated by protoc-gen-go. DO NOT EDIT.
// source: controller.proto

package protogen

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MoveDetails_Direction int32

const (
	MoveDetails_FORWARD  MoveDetails_Direction = 0
	MoveDetails_BACKWARD MoveDetails_Direction = 1
	MoveDetails_LEFT     MoveDetails_Direction = 2
	MoveDetails_RIGHT    MoveDetails_Direction = 3
)

var MoveDetails_Direction_name = map[int32]string{
	0: "FORWARD",
	1: "BACKWARD",
	2: "LEFT",
	3: "RIGHT",
}

var MoveDetails_Direction_value = map[string]int32{
	"FORWARD":  0,
	"BACKWARD": 1,
	"LEFT":     2,
	"RIGHT":    3,
}

func (x MoveDetails_Direction) String() string {
	return proto.EnumName(MoveDetails_Direction_name, int32(x))
}

func (MoveDetails_Direction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{0, 0}
}

type MoveDetails struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveDetails) Reset()         { *m = MoveDetails{} }
func (m *MoveDetails) String() string { return proto.CompactTextString(m) }
func (*MoveDetails) ProtoMessage()    {}
func (*MoveDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{0}
}

func (m *MoveDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveDetails.Unmarshal(m, b)
}
func (m *MoveDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveDetails.Marshal(b, m, deterministic)
}
func (m *MoveDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveDetails.Merge(m, src)
}
func (m *MoveDetails) XXX_Size() int {
	return xxx_messageInfo_MoveDetails.Size(m)
}
func (m *MoveDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveDetails.DiscardUnknown(m)
}

var xxx_messageInfo_MoveDetails proto.InternalMessageInfo

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("protogen.MoveDetails_Direction", MoveDetails_Direction_name, MoveDetails_Direction_value)
	proto.RegisterType((*MoveDetails)(nil), "protogen.MoveDetails")
	proto.RegisterType((*Empty)(nil), "protogen.Empty")
}

func init() {
	proto.RegisterFile("controller.proto", fileDescriptor_ed7f10298fa1d90f)
}

var fileDescriptor_ed7f10298fa1d90f = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xce, 0xcf, 0x2b,
	0x29, 0xca, 0xcf, 0xc9, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53,
	0xe9, 0xa9, 0x79, 0x4a, 0x5e, 0x5c, 0xdc, 0xbe, 0xf9, 0x65, 0xa9, 0x2e, 0xa9, 0x25, 0x89, 0x99,
	0x39, 0xc5, 0x4a, 0xd6, 0x5c, 0x9c, 0x2e, 0x99, 0x45, 0xa9, 0xc9, 0x25, 0x99, 0xf9, 0x79, 0x42,
	0xdc, 0x5c, 0xec, 0x6e, 0xfe, 0x41, 0xe1, 0x8e, 0x41, 0x2e, 0x02, 0x0c, 0x42, 0x3c, 0x5c, 0x1c,
	0x4e, 0x8e, 0xce, 0xde, 0x60, 0x1e, 0xa3, 0x10, 0x07, 0x17, 0x8b, 0x8f, 0xab, 0x5b, 0x88, 0x00,
	0x93, 0x10, 0x27, 0x17, 0x6b, 0x90, 0xa7, 0xbb, 0x47, 0x88, 0x00, 0xb3, 0x12, 0x3b, 0x17, 0xab,
	0x6b, 0x6e, 0x41, 0x49, 0xa5, 0x91, 0x09, 0x17, 0x93, 0x8b, 0x91, 0x90, 0x1e, 0x17, 0x0b, 0xc8,
	0x68, 0x21, 0x51, 0x3d, 0x98, 0x6d, 0x7a, 0x48, 0x56, 0x49, 0xf1, 0x23, 0x84, 0xc1, 0xba, 0x9c,
	0x78, 0xa2, 0xb8, 0xf4, 0xf4, 0x61, 0x62, 0x49, 0x6c, 0x60, 0x96, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0xb3, 0x72, 0x39, 0x00, 0xbd, 0x00, 0x00, 0x00,
}
