// Code generated by protoc-gen-go. DO NOT EDIT.
// source: controller.proto

package protogen

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Move_Direction int32

const (
	Move_FORWARD  Move_Direction = 0
	Move_BACKWARD Move_Direction = 1
	Move_LEFT     Move_Direction = 2
	Move_RIGHT    Move_Direction = 3
)

var Move_Direction_name = map[int32]string{
	0: "FORWARD",
	1: "BACKWARD",
	2: "LEFT",
	3: "RIGHT",
}

var Move_Direction_value = map[string]int32{
	"FORWARD":  0,
	"BACKWARD": 1,
	"LEFT":     2,
	"RIGHT":    3,
}

func (x Move_Direction) String() string {
	return proto.EnumName(Move_Direction_name, int32(x))
}

func (Move_Direction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{0, 0}
}

type Move struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Move) Reset()         { *m = Move{} }
func (m *Move) String() string { return proto.CompactTextString(m) }
func (*Move) ProtoMessage()    {}
func (*Move) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed7f10298fa1d90f, []int{0}
}

func (m *Move) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Move.Unmarshal(m, b)
}
func (m *Move) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Move.Marshal(b, m, deterministic)
}
func (m *Move) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Move.Merge(m, src)
}
func (m *Move) XXX_Size() int {
	return xxx_messageInfo_Move.Size(m)
}
func (m *Move) XXX_DiscardUnknown() {
	xxx_messageInfo_Move.DiscardUnknown(m)
}

var xxx_messageInfo_Move proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("protogen.Move_Direction", Move_Direction_name, Move_Direction_value)
	proto.RegisterType((*Move)(nil), "protogen.Move")
}

func init() {
	proto.RegisterFile("controller.proto", fileDescriptor_ed7f10298fa1d90f)
}

var fileDescriptor_ed7f10298fa1d90f = []byte{
	// 120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xce, 0xcf, 0x2b,
	0x29, 0xca, 0xcf, 0xc9, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53,
	0xe9, 0xa9, 0x79, 0x4a, 0xce, 0x5c, 0x2c, 0xbe, 0xf9, 0x65, 0xa9, 0x4a, 0xd6, 0x5c, 0x9c, 0x2e,
	0x99, 0x45, 0xa9, 0xc9, 0x25, 0x99, 0xf9, 0x79, 0x42, 0xdc, 0x5c, 0xec, 0x6e, 0xfe, 0x41, 0xe1,
	0x8e, 0x41, 0x2e, 0x02, 0x0c, 0x42, 0x3c, 0x5c, 0x1c, 0x4e, 0x8e, 0xce, 0xde, 0x60, 0x1e, 0xa3,
	0x10, 0x07, 0x17, 0x8b, 0x8f, 0xab, 0x5b, 0x88, 0x00, 0x93, 0x10, 0x27, 0x17, 0x6b, 0x90, 0xa7,
	0xbb, 0x47, 0x88, 0x00, 0x73, 0x12, 0x1b, 0xd8, 0x38, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xec, 0x68, 0x3a, 0x9d, 0x69, 0x00, 0x00, 0x00,
}
